---
apiVersion: batch/v1
kind: Job
metadata:
  name: cert-generator
  namespace: default
spec:
  template:
    spec:
      serviceAccountName: cert-gen-sa
      containers:
        - name: certgen
          image: k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.3.0
          resources:
            requests:
              cpu: "250m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "128Mi"
          args:
            - create
            - --host=validate-registry.default.svc
            - --namespace=default
            - --cert-name=tls.crt
            - --key-name=tls.key
            - --secret-name=validate-registry-tls
          volumeMounts:
            - name: certs
              mountPath: /certs
      restartPolicy: OnFailure
      volumes:
        - name: certs
          emptyDir:
            sizeLimit: 1Mi