apiVersion: batch/v1
kind: CronJob
metadata:
  name: bad-cronjob
spec:
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: test
            image: docker.io/nginx:latest
            command: ["echo", "hello"]
          restartPolicy: OnFailure