apiVersion: batch/v1
kind: CronJob
metadata:
  name: good-cronjob
spec:
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: test
            image: registry.kupher.io/nginx:latest
            command: ["echo", "hello"]
          restartPolicy: OnFailure