apiVersion: batch/v1
kind: Job
metadata:
  name: good-job
spec:
  template:
    spec:
      containers:
      - name: nginx
        image: registry.kupher.io/nginx:latest
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
