apiVersion: v1
kind: Pod
metadata:
  name: good-pod
  namespace: default
spec:
  automountServiceAccountToken: false
  containers:
    - name: nginx
      image: registry.kupher.io/nginx
      resources:
        requests:
          cpu: "250m"
          memory: "64Mi"
        limits:
          cpu: "500m"
          memory: "128Mi"
