name: Test Webhook in KinD

on:
  push:
    branches: [main]
  workflow_dispatch:  #Manual trigger support

jobs:
  test-k8s:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install Dependencies
        run: go mod tidy

      - name: Run Unit Tests
        run: go test ./... -v

      - name: Set up KinD Cluster
        uses: helm/kind-action@v1.8.0
        with:
          cluster_name: kind

      - name: Build Docker Image
        run: docker build -t webhook:test .

      - name: Load Image into KinD
        run: kind load docker-image webhook:test

      - name: Deploy Cert-Gen
        run: |
          kubectl apply -f deploy/cert-gen/
      
      - name: Wait for TLS Secret
        run: |
          echo "Waiting for TLS secret to be created..."
          for i in {1..20}; do
            kubectl get secret validate-registry-tls -n default && break
            echo "Waiting..."
            sleep 3
          done

      - name: Extract CA Bundle
        id: ca
        run: |
          # Extract and Base64-encode ca.crt from the secret
          kubectl get secret validate-registry-tls -n default -o jsonpath='{.data.ca\.crt}' > ca.txt
          echo "CA_BUNDLE=$(cat ca.txt)" >> $GITHUB_ENV

      - name: Inject CA Bundle into Webhook Configuration
        run: |
          # Replace placeholder with actual base64 ca.crt
          envsubst < deploy/controller/webhook-config.yaml.tpl > webhook-final.yaml

          # Apply the dynamic ValidatingWebhookConfiguration
          # kubectl apply -f webhook-final.yaml

      - name: Deploy controller
        run: |
          ls -l
          kubectl apply -f deploy/controller/configmap.yaml
          kubectl apply -f deploy/controller/deployment.yaml
          kubectl apply -f deploy/controller/service.yaml
          kubectl apply -f webhook-final.yaml

      - name: Wait for Pods to be Ready
        run: |
          kubectl wait --for=condition=ready pod -l app=validate-registry --timeout=60s

      - name: Run test pod
        run: |
          kubectl apply -f deploy/test/